"""Names of every event AgroFarm pushes over the live channel.

The frontend imports the same list, so keep both sides in step.
"""

VEHICLE_LOCATION_UPDATED = "VEHICLE_LOCATION_UPDATED"
SHIPMENT_CREATED = "SHIPMENT_CREATED"
SHIPMENT_UPDATED = "SHIPMENT_UPDATED"
TELEMETRY_UPDATED = "TELEMETRY_UPDATED"
ALERT_CREATED = "ALERT_CREATED"
EMERGENCY_CREATED = "EMERGENCY_CREATED"
EMERGENCY_UPDATED = "EMERGENCY_UPDATED"
INVENTORY_UPDATED = "INVENTORY_UPDATED"
NOTIFICATION_CREATED = "NOTIFICATION_CREATED"

ALL_EVENTS = [
    VEHICLE_LOCATION_UPDATED,
    SHIPMENT_CREATED,
    SHIPMENT_UPDATED,
    TELEMETRY_UPDATED,
    ALERT_CREATED,
    EMERGENCY_CREATED,
    EMERGENCY_UPDATED,
    INVENTORY_UPDATED,
    NOTIFICATION_CREATED,
]
